POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "kumar_atul",
    "password": "helloworld",
    "email": "atul@gmail.com",
    "phone": 9809809800
}

###

GET http://localhost:3000/

###

POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "anik_ghosh",
    "password": "helloworld",
    "email": "anik@gmail.com",
    "phone": 9809809800
}

###

POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "ghosh",
    "password": "anik",
    "email": "ghosh@gmail.com",
    "phone": 9809809800
}

###

POST http://localhost:3000/users/createuser
Content-Type: application/json

{
    "username": "anik",
    "password": "anik",
    "email": "helloo@gmail.com",
    "phone": 9809809800
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "anik",
    "password": "anik"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "anik",
    "password": "anikgh"
}

###
